server-info: "Server list"
UpdateInfoProvide: "Server information update method. Options: Simple, Details"
sync-player: "Display the total player count of all servers in MOTD"
ServerCloseTransfer: "Transfer to a specified server when this server is closed"
ServerCloseTransfer.enable: "Enable this feature"
ServerCloseTransfer.showTitle: "Notification message"
ServerCloseTransfer.ip: "Target server IP"
ServerCloseTransfer.port: "Target server port"
ServerCloseTransfer.TransferMode: |-
  When set to true, the system will search for an available server in ServerList to transfer to.
  When set to false, it will transfer to the server defined by ServerCloseTransfer.ip & port.
ServerCloseTransfer.ServerList: |-
  List of transferable servers. The names should match the name defined in server-info.
  Example: If the name is defined as lobby1, then enter lobby1.