server-info: "服务器列表"
UpdateInfoProvide: "服务器信息更新方式 可选: Simple, Details"
sync-player: "在MOTD显示所有服务器的玩家数量总数"
ServerCloseTransfer: "本服务器关闭时传送到指定服务器"
ServerCloseTransfer.enable: "是否启用"
ServerCloseTransfer.showTitle: "提示内容"
ServerCloseTransfer.ip: "目标服务器IP"
ServerCloseTransfer.port: "目标服务器端口"
ServerCloseTransfer.TransferMode: |-
  为 true 时将在 ServerList 中寻找可用的服务器进行转移
  为 false 时则会转移到 ServerCloseTransfer.ip&prot 定义的服务器中
ServerCloseTransfer.use-WaterdogPE: 如果使用 WaterdogPE 则启用该功能
ServerCloseTransfer.ServerList: |-
  可转移的服务器列表，名称为 server-info 中定义的 name
  例如：name 定义了 lobby1 就填写 lobby1